//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public Nullable<int> DeveloperId { get; set; }
        public Nullable<int> SubtaskId { get; set; }
        public string FeedbackStr { get; set; }
        public Nullable<double> Positivity { get; set; }
    }
}
